export const HUB = {
    id: "ipamorelin",
    site: {
        name: "Hub Ipamorelin",
        logo: "IPAMORELIN",
        brand: "Suplementos Mais Baratos",
        domain: "https://ipamorelin.suplementosmaisbaratos.com.br",
        whatsapp: "5521972232170",
        whatsappDisplay: "+55 21 97223-2170",
        defaultMsg:
            "Olá! Vim pelo Hub Ipamorelin e quero agendar minha avaliação educacional gratuita sobre peptídeos.",
    },
    drug: { name: "Ipamorelin", alt: "NNC 26-0161" },
    navLinks: [
        { to: "/o-que-e-ipamorelin", label: "O que é" },
        { to: "/estudos-clinicos", label: "Estudos" },
        { to: "/ipamorelin-vs-sermorelin", label: "vs Sermorelin" },
        { to: "/ipamorelin-preco", label: "Preço" },
        { to: "/onde-comprar-ipamorelin", label: "Disponibilidade" },
        { to: "/faq", label: "FAQ" },
    ],
    hubLinks: [
        { to: "/", label: "Ipamorelin — Hub Científico", anchor: "ipamorelin" },
        { to: "/o-que-e-ipamorelin", label: "O que é ipamorelin", anchor: "ipamorelin o que é" },
        { to: "/como-funciona", label: "Como funciona a ipamorelin", anchor: "ipamorelin como funciona" },
        { to: "/estudos-clinicos", label: "Estudos clínicos da ipamorelin", anchor: "ipamorelin estudos clínicos" },
        { to: "/ipamorelin-vs-sermorelin", label: "Ipamorelin ou Sermorelin", anchor: "ipamorelin vs sermorelin" },
        { to: "/efeitos-colaterais", label: "Efeitos colaterais da ipamorelin", anchor: "ipamorelin efeitos colaterais" },
        { to: "/ipamorelin-preco", label: "Preço da ipamorelin", anchor: "ipamorelin preço" },
        { to: "/onde-comprar-ipamorelin", label: "Onde comprar ipamorelin", anchor: "ipamorelin onde comprar" },
        { to: "/consultoria-peptideos", label: "Consultoria em peptídeos", anchor: "consultoria em peptídeos" },
        { to: "/faq", label: "Perguntas frequentes", anchor: "ipamorelin perguntas frequentes" },
    ],
    disclaimer:
        "Conteúdo exclusivamente educacional. A ipamorelin não possui registro na ANVISA nem aprovação terapêutica em nenhum país. Este site não vende nem intermedia peptídeos. Consulte sempre um médico.",
    inlineLinks: [
        { term: "ipamorelin", to: "/", title: "Ipamorelin — Hub Científico" },
        { term: "sermorelin", to: "/ipamorelin-vs-sermorelin", title: "ipamorelin vs sermorelin" },
        { term: "preço oficial", to: "/ipamorelin-preco", title: "ipamorelin preço" },
        { term: "onde comprar", to: "/onde-comprar-ipamorelin", title: "ipamorelin onde comprar" },
        { term: "efeitos colaterais", to: "/efeitos-colaterais", title: "ipamorelin efeitos colaterais" },
        { term: "mecanismo", to: "/como-funciona", title: "ipamorelin como funciona" },
        { term: "consultoria educacional", to: "/consultoria-peptideos", title: "consultoria em peptídeos" },
        { term: "CJC-1295", to: "/ipamorelin-vs-sermorelin", title: "ipamorelin e CJC-1295" },
    ],
    marquee: [
        "GHS-R1A", "GH PULSÁTIL", "IGF-1", "PENTAPEPTÍDEO", "SECRETAGOGO SELETIVO",
        "SEM CORTISOL", "WADA — CLASSE S2", "SEM REGISTRO ANVISA", "ESTUDOS FASE 1/2",
        "PEPTÍDEO EXPERIMENTAL", "EIXO GH", "CIÊNCIA, NÃO HYPE",
    ],
    hero: {
        kicker: "Hub científico · Peptídeos & eixo GH",
        l1: "IPAMORELIN:",
        l2: "CIÊNCIA,",
        l3: "NÃO HYPE.",
        subPre: "O guia técnico independente sobre o secretagogo seletivo de hormônio do crescimento",
        subMono: "GHS-R1a · GH · IGF-1",
        subPos: "— mecanismo, evidências, segurança e o status regulatório real no Brasil.",
    },
    stats: [
        { value: "5", label: "aminoácidos — um pentapeptídeo sintético" },
        { value: "~2 h", label: "meia-vida curta observada nos estudos" },
        { value: "S2", label: "classe de proibição na lista da WADA" },
        { value: "0", label: "registros na ANVISA até hoje" },
    ],
    mech: {
        kicker: "Infográfico · Mecanismo",
        h2a: "Um receptor.",
        h2b: "Um eixo inteiro.",
        p: "A ipamorelin se liga ao receptor GHS-R1a — o mesmo da ghrelina — na hipófise e dispara a liberação pulsátil de GH, que por sua vez estimula a produção de IGF-1. O diferencial histórico da molécula é a seletividade: nos estudos, o pulso de GH veio sem elevação significativa de cortisol ou prolactina.",
        items: [
            { t: "GHS-R1a", d: "Receptor da ghrelina na hipófise — o gatilho do pulso" },
            { t: "GH", d: "Liberação pulsátil de hormônio do crescimento" },
            { t: "IGF-1", d: "Mediação periférica dos efeitos atribuídos ao eixo" },
        ],
        moreLabel: "Mecanismo completo no Cap. 02",
        moreTo: "/como-funciona",
    },
    diagram: {
        fig: "FIG. 01 — O eixo GHS-R1a → GH → IGF-1",
        aria: "Diagrama do mecanismo da ipamorelin: receptor GHS-R1a, pulso de GH e mediação por IGF-1",
        centerTop: "PENTAPEPTÍDEO",
        centerName: "IPAMO",
        centerSub: "SELECTIVE GHS",
        nodes: [
            { id: "ghsr", x: 90, y: 80, label: "GHS-R1a", desc: "Receptor da ghrelina" },
            { id: "gh", x: 90, y: 260, label: "GH", desc: "Pulso hipofisário" },
            { id: "igf1", x: 510, y: 170, label: "IGF-1", desc: "Mediação periférica" },
        ],
    },
    market: {
        h2a: "Procurando preço ou onde comprar?",
        h2b: "Leia isto primeiro.",
        p: "Não existe preço oficial nem canal legal de venda da ipamorelin — no Brasil e em nenhum país. As ofertas de 'peptídeos para pesquisa' circulam fora do marco sanitário e já foram alvo de alertas e ações da ANVISA. Preferimos perder o clique a perder a honestidade.",
        l1: { to: "/ipamorelin-preco", label: "Por que não há preço oficial", title: "ipamorelin preço" },
        l2: { to: "/onde-comprar-ipamorelin", label: "O status real de disponibilidade", title: "ipamorelin onde comprar" },
        fig: "FIG. 02 — Pesquisa sob escudo: ciência precisa de regulação",
    },
    homeSeo: {
        title: "Ipamorelin — Hub Científico e Consultoria em Peptídeos",
        desc: "Guia técnico independente sobre ipamorelin: receptor GHS-R1a, eixo GH/IGF-1, estudos, seletividade, segurança e status na ANVISA. Avaliação educacional gratuita.",
    },
    faqPage: {
        seoTitle: "FAQ Ipamorelin — Perguntas Frequentes Respondidas com Ciência",
        seoDesc: "Ipamorelin é aprovada? Para que serve? Como tomar? Qual o preço? Onde comprar? Ipamorelin ou sermorelin? Respostas diretas e honestas para as perguntas mais buscadas.",
        kicker: "Perguntas frequentes · respostas sem filtro",
        h1a: "O QUE O BRASIL",
        h1b: "PERGUNTA SOBRE",
        h1neon: "IPAMORELIN",
        sub: "Reunimos as dúvidas mais buscadas no Google e respondemos com base nos estudos e no cenário regulatório real — inclusive quando a resposta não é a que você esperava.",
    },
    faqs: [
        { q: "A ipamorelin é aprovada no Brasil?", a: "Não. A ipamorelin não possui registro na ANVISA nem aprovação terapêutica em nenhum país. O programa de desenvolvimento farmacêutico original foi descontinuado ainda na fase 2, e qualquer produto vendido com esse nome opera fora do marco sanitário." },
        { q: "O que é a ipamorelin?", a: "É um pentapeptídeo sintético (5 aminoácidos) da classe dos secretagogos de GH: ele se liga ao receptor GHS-R1a — o receptor da ghrelina — e estimula a hipófise a liberar hormônio do crescimento de forma pulsátil. Seu diferencial nos estudos foi a seletividade, sem elevar cortisol ou prolactina." },
        { q: "Para que serve a ipamorelin?", a: "Nos estudos, a finalidade investigada foi estimular a liberação de GH (e, em um programa descontinuado, tratar íleo pós-operatório). As alegações populares — massa muscular, queima de gordura, sono, 'antienvelhecimento' — são extrapolações da fisiologia do GH/IGF-1 e não têm ensaios clínicos robustos que as comprovem." },
        { q: "Ipamorelin: como tomar?", a: "Não existe orientação de uso aprovada, porque a molécula não tem registro em nenhum país. Nos protocolos de pesquisa, a administração foi intravenosa ou subcutânea, sempre sob supervisão médica. Fora de ensaios, não há dose segura estabelecida — e produtos do mercado informal não têm conteúdo verificado." },
        { q: "Quais são os efeitos colaterais da ipamorelin?", a: "Nos estudos disponíveis, os eventos mais relatados foram rubor (flushing), dor de cabeça e reações no local de aplicação, geralmente leves. As preocupações teóricas envolvem a elevação crônica de GH/IGF-1: retenção hídrica, resistência à insulina e estimulação de crescimento celular — motivo pelo qual o uso sem acompanhamento é arriscado." },
        { q: "Ipamorelin ou sermorelin: qual a diferença?", a: "São classes distintas: a ipamorelin imita a ghrelina (receptor GHS-R1a), enquanto a sermorelina é um análogo de GHRH (outro eixo de estímulo do GH). Nenhuma das duas tem registro na ANVISA. Detalhamos a comparação no capítulo 04." },
        { q: "Qual é o preço da ipamorelin?", a: "Não existe preço oficial: sem registro regulatório, nenhum laboratório pode precificar ou vender a molécula. Valores anunciados em sites e redes sociais referem-se a produtos irregulares, sem garantia de identidade, pureza ou dose." },
        { q: "Onde comprar ipamorelin com segurança?", a: "Não existe canal legal de venda — no Brasil e no mundo. A rota legítima para questões ligadas ao eixo GH é a avaliação médica (endocrinologista), que dispõe de opções aprovadas e exames para investigar deficiência real de GH." },
        { q: "Ipamorelin é proibida no esporte?", a: "Sim. A ipamorelin consta da Lista de Substâncias Proibidas da WADA (classe S2 — hormônios e fatores de crescimento), dentro e fora de competição. Atletas testados podem sofrer sanções mesmo sem intenção de doping." },
    ],
    articles: [
        {
            slug: "o-que-e-ipamorelin",
            chapter: "01",
            kicker: "Fundamentos",
            title: "O que é Ipamorelin? O secretagogo de GH explicado",
            description: "Entenda o que é a ipamorelin, o pentapeptídeo secretagogo seletivo de hormônio do crescimento (receptor GHS-R1a), sua origem na pesquisa farmacêutica e seu status regulatório no Brasil.",
            keyword: "ipamorelin o que é",
            readTime: "6 min",
            lede: "A ipamorelin é um pentapeptídeo sintético que estimula a liberação de hormônio do crescimento — e virou nome frequente em fóruns de performance. Aqui está o que a ciência realmente documenta sobre ela.",
            sections: [
                { h: "Um pentapeptídeo da classe dos secretagogos", p: ["A ipamorelin é um peptídeo sintético de cinco aminoácidos (um pentapeptídeo) desenvolvido pela Novo Nordisk no fim dos anos 1990, sob o código NNC 26-0161. Ela pertence à classe dos secretagogos de GH: moléculas que estimulam a hipófise a liberar hormônio do crescimento.", "Seu alvo é o receptor GHS-R1a — o mesmo receptor da ghrelina, o 'hormônio da fome', que também participa da regulação natural do GH."] },
                { h: "O diferencial que tornou a molécula famosa", p: ["Nos estudos farmacológicos, a ipamorelin se destacou pela seletividade: ela elevou o GH de forma pulsátil sem aumentar significativamente cortisol, prolactina ou ACTH — efeitos colaterais hormonais comuns em secretagogos mais antigos, como o GHRP-6.", "Foi essa seletividade que a transformou em referência dentro da classe — e, anos depois, em nome recorrente do mercado informal de peptídeos."] },
                { h: "Por que ela nunca virou medicamento", p: ["O programa de desenvolvimento clínico da ipamorelin investigou, entre outras indicações, o íleo pós-operatório (paralisia intestinal após cirurgias). Os estudos de fase 2 não atingiram a eficácia necessária e o desenvolvimento foi descontinuado.", "Resultado: a molécula nunca foi aprovada para nenhuma indicação terapêutica, em nenhum país — nem FDA, nem EMA, nem ANVISA."] },
                { h: "Status regulatório no Brasil", p: ["A ipamorelin não possui registro na ANVISA e não consta das listas de insumos permitidos para manipulação em farmácias magistrais. A venda de produtos rotulados como 'ipamorelin' — frequentemente anunciados como 'para pesquisa' — ocorre fora do marco sanitário.", "Detalhamos os riscos desse mercado e os caminhos legítimos nas páginas sobre preço e disponibilidade."] },
            ],
            stat: { value: "5 aa", label: "apenas cinco aminoácidos — um dos menores secretagogos de GH já sintetizados" },
            faqs: [
                { q: "Ipamorelin é um medicamento aprovado?", a: "Não. A ipamorelin nunca foi aprovada para uso terapêutico em nenhum país; o desenvolvimento farmacêutico foi descontinuado na fase 2." },
                { q: "Ipamorelin é o mesmo que GH?", a: "Não. GH é o hormônio em si. A ipamorelin é um estimulante da liberação natural de GH pela hipófise — um secretagogo, não o hormônio." },
            ],
            refs: [
                { label: "PubMed — ipamorelin (busca na base do NIH)", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ipamorelin" },
                { label: "ClinicalTrials.gov — estudos com ipamorelin", url: "https://clinicaltrials.gov/search?term=ipamorelin" },
            ],
        },
        {
            slug: "como-funciona",
            chapter: "02",
            kicker: "Mecanismo de ação",
            title: "Como funciona a Ipamorelin? O eixo GHS-R1a, GH e IGF-1",
            description: "Entenda como a ipamorelin atua no receptor GHS-R1a (receptor da ghrelina), dispara o pulso de GH e influencia o IGF-1 — e por que sua seletividade hormonal é o diferencial histórico.",
            keyword: "ipamorelin como funciona",
            readTime: "7 min",
            diagram: true,
            lede: "Um receptor, um pulso, um eixo. O mecanismo da ipamorelin imita um sinal natural do corpo — e é essa elegância farmacológica que sustenta a reputação da molécula.",
            sections: [
                { h: "GHS-R1a: o receptor da ghrelina", p: ["A ipamorelin se liga ao receptor GHS-R1a, presente na hipófise e no hipotálamo. É o mesmo receptor ativado pela ghrelina, hormônio produzido pelo estômago que, além de estimular a fome, participa da regulação da liberação de GH.", "Ao ativar esse receptor, a molécula 'engana' a hipófise com um sinal que o corpo já conhece — por isso a resposta tende a seguir o padrão fisiológico."] },
                { h: "O pulso de GH", p: ["Ativada a hipófise, o resultado é a liberação de GH em formato pulsátil — picos intermitentes, como ocorre naturalmente durante o sono profundo e o exercício intenso, e não uma elevação contínua.", "A meia-vida curta da molécula (cerca de 2 horas nos estudos) reforça esse padrão: o estímulo vem e passa, em vez de pressionar o eixo sem pausa."] },
                { h: "IGF-1: o mensageiro periférico", p: ["Boa parte dos efeitos atribuídos ao GH é mediada pelo IGF-1 (fator de crescimento semelhante à insulina tipo 1), produzido principalmente no fígado em resposta ao pulso de GH.", "É no eixo GH → IGF-1 que a literatura ancora discussões sobre síntese proteica, metabolismo de gordura e recuperação de tecidos — embora, no caso da ipamorelin, sem ensaios clínicos de desfecho que confirmem esses benefícios em humanos."] },
                { h: "A seletividade que virou assinatura", p: ["Secretagogos antigos elevavam junto cortisol e prolactina — hormônios de estresse e efeitos indesejados. Nos estudos comparativos, a ipamorelin manteve esses dois praticamente inalterados enquanto elevava o GH.", "Essa seletividade é o dado farmacológico mais citado da molécula — e também o mais distorcido no marketing informal, que transforma 'seletiva' em 'segura', salto que a ciência não autoriza."] },
            ],
            stat: { value: "~2 h", label: "de meia-vida nos estudos — estímulo curto e pulsátil, não contínuo" },
            faqs: [
                { q: "A ipamorelin aumenta GH de forma natural?", a: "Ela estimula a hipófise a liberar o GH do próprio corpo, em padrão pulsátil — diferente de injetar GH sintético. Mas 'estimular o próprio eixo' não significa 'livre de riscos'." },
                { q: "Ipamorelin aumenta cortisol?", a: "Nos estudos farmacológicos, não de forma significativa — esse foi justamente o diferencial de seletividade em relação a secretagogos mais antigos." },
            ],
            refs: [
                { label: "PubMed — ipamorelin GHS-R1a", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ipamorelin" },
                { label: "ClinicalTrials.gov — estudos com ipamorelin", url: "https://clinicaltrials.gov/search?term=ipamorelin" },
            ],
        },
        {
            slug: "estudos-clinicos",
            chapter: "03",
            kicker: "Evidência clínica",
            title: "Estudos clínicos da Ipamorelin: o que existe (e o que falta)",
            description: "O mapa honesto da evidência sobre ipamorelin: estudos de fase 1 e 2, o programa descontinuado para íleo pós-operatório e por que as alegações populares não têm ensaios de desfecho.",
            keyword: "ipamorelin estudos clínicos",
            readTime: "8 min",
            lede: "Diferente de moléculas com programas de fase 3, a ipamorelin tem um corpo de evidência pequeno e antigo. Separar o que foi medido do que é repetido na internet é o objetivo deste capítulo.",
            sections: [
                { h: "Fase 1: farmacologia em humanos", p: ["Os primeiros estudos em humanos, conduzidos no fim dos anos 1990, caracterizaram a farmacologia da molécula: elevação dose-dependente de GH, padrão pulsátil, meia-vida curta (cerca de 2 horas) e o perfil seletivo sem elevação relevante de cortisol e prolactina.", "Esses estudos responderam 'o que a molécula faz no corpo' — não 'para que ela serve clinicamente'."] },
                { h: "Fase 2: a indicação que não vingou", p: ["A Novo Nordisk investigou a ipamorelin para íleo pós-operatório, uma paralisia transitória do intestino comum após cirurgias abdominais. Os ensaios de fase 2 não demonstraram eficácia suficiente, e o programa foi descontinuado.", "Esse desfecho explica um ponto frequentemente ignorado: a ipamorelin não é um 'medicamento novo a caminho' — é uma molécula cujo desenvolvimento formal parou há décadas."] },
                { h: "O que NÃO existe na literatura", p: ["Não há ensaios randomizados de porte avaliando ipamorelin para ganho de massa muscular, perda de gordura, qualidade de sono, recuperação ou 'antienvelhecimento'. Todas essas alegações circulam como extrapolação da fisiologia conhecida do GH/IGF-1 — não como resultado medido.", "Também não existem dados de segurança de longo prazo em humanos, nem estudos sobre uso crônico fora de protocolos — exatamente o padrão de uso vendido no mercado informal."] },
                { h: "Como ler promessas com esse cenário", p: ["A régua correta: fisiologia plausível não é evidência clínica. O GH de fato participa de metabolismo e recuperação — mas transformar isso em promessa de resultado exigiria ensaios que nunca foram feitos com essa molécula.", "Nossa consultoria educacional ajuda a interpretar exatamente esse tipo de distância entre mecanismo e promessa, com avaliação gratuita."] },
            ],
            stat: { value: "0", label: "ensaios clínicos de desfecho (massa muscular, gordura, sono) conduzidos com ipamorelin em humanos" },
            faqs: [
                { q: "Existem estudos provando que ipamorelin funciona para massa muscular?", a: "Não. Não há ensaios clínicos de desfecho com essa finalidade. O que existe são estudos farmacológicos mostrando elevação de GH — o salto para resultados estéticos ou de performance é extrapolação sem comprovação." },
                { q: "Por que a ipamorelin não virou remédio?", a: "O programa de desenvolvimento (para íleo pós-operatório) não atingiu a eficácia necessária na fase 2 e foi descontinuado. Nenhum outro programa clínico formal foi concluído desde então." },
            ],
            refs: [
                { label: "PubMed — ipamorelin (busca na base do NIH)", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ipamorelin" },
                { label: "ClinicalTrials.gov — estudos com ipamorelin", url: "https://clinicaltrials.gov/search?term=ipamorelin" },
            ],
        },
        {
            slug: "ipamorelin-vs-sermorelin",
            chapter: "04",
            kicker: "Comparativo técnico",
            title: "Ipamorelin ou Sermorelin: a comparação técnica",
            description: "Ipamorelin ou sermorelin? Comparação objetiva entre as duas classes de secretagogos de GH: receptor-alvo, evidência, histórico regulatório e o que se sabe sobre a combinação com CJC-1295.",
            keyword: "ipamorelin vs sermorelin",
            readTime: "7 min",
            table: {
                head: ["Critério", "Ipamorelin", "Sermorelin"],
                rows: [
                    ["Classe", "Secretagogo via receptor da ghrelina (GHS-R1a)", "Análogo de GHRH (29 aminoácidos)"],
                    ["Eixo de ação", "Imita a ghrelina na hipófise", "Imita o GHRH hipotalâmico"],
                    ["Seletividade hormonal", "Sem elevação relevante de cortisol/prolactina (estudos)", "Também considerada seletiva dentro da classe GHRH"],
                    ["Histórico regulatório", "Nunca aprovada em nenhum país", "Teve aprovação FDA nos anos 1990 (Geref) — produto descontinuado"],
                    ["Status no Brasil", "Sem registro ANVISA", "Sem registro ANVISA"],
                    ["Evidência em desfechos", "Sem ensaios de composição corporal/performance", "Estudos antigos em deficiência de GH pediátrica"],
                ],
            },
            lede: "É o duelo clássico dos secretagogos de GH — e também um dos temas com mais desinformação por clique. As duas moléculas, lado a lado, sem torcida.",
            sections: [
                { h: "Duas classes, dois gatilhos diferentes", p: ["Embora vendidas no mesmo 'pacote' pelo mercado informal, ipamorelin e sermorelina agem por vias distintas. A ipamorelin imita a ghrelina (receptor GHS-R1a); a sermorelina imita o GHRH, o hormônio hipotalâmico que é o outro grande estimulante natural do GH.", "Na fisiologia, GHRH e ghrelina trabalham em conjunto — daí a ideia, popular no meio, de combinar moléculas das duas classes."] },
                { h: "O que diz o histórico de cada uma", p: ["A sermorelina chegou mais longe regulatoriamente: foi aprovada pela FDA nos anos 1990 (nome comercial Geref) para avaliação e tratamento de deficiência de GH em crianças — mas o produto foi descontinuado pelo fabricante, e hoje não há versão registrada no mercado, inclusive no Brasil.", "A ipamorelin, como vimos, nunca concluiu um programa de desenvolvimento. Ambas, portanto, estão hoje fora do marco sanitário brasileiro."] },
                { h: "E a famosa combinação com CJC-1295?", p: ["O 'stack' ipamorelin + CJC-1295 (um análogo de GHRH) repete a lógica fisiológica: estimular o eixo pelos dois gatilhos ao mesmo tempo. A sinergia é teoricamente plausível — e clinicamente nunca testada: não existe ensaio clínico publicado da combinação.", "Ou seja: quem usa está, na prática, conduzindo um experimento consigo mesmo, com produtos de procedência não verificada."] },
            ],
            stat: { value: "2 vias", label: "GHRH e ghrelina — os dois gatilhos naturais de GH que essas moléculas imitam" },
            faqs: [
                { q: "Ipamorelin é melhor que sermorelin?", a: "Não há estudo comparativo direto entre as duas. Farmacologicamente, a ipamorelin se destacou pela seletividade hormonal; a sermorelina teve um histórico regulatório mais longo (FDA, anos 1990), mas seu produto foi descontinuado." },
                { q: "Posso comprar sermorelin ou ipamorelin na farmácia?", a: "Não. Nenhuma das duas possui registro na ANVISA — qualquer oferta no Brasil é irregular." },
            ],
            refs: [
                { label: "PubMed — ipamorelin vs sermorelin", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ipamorelin+sermorelin" },
                { label: "WADA — Lista de Substâncias Proibidas", url: "https://www.wada-ama.org/en/prohibited-list" },
            ],
        },
        {
            slug: "efeitos-colaterais",
            chapter: "05",
            kicker: "Segurança",
            title: "Efeitos colaterais da Ipamorelin: o que se sabe",
            description: "Perfil de segurança da ipamorelin: eventos relatados nos estudos, os riscos teóricos da elevação crônica de GH/IGF-1 e a proibição no esporte pela WADA.",
            keyword: "ipamorelin efeitos colaterais",
            readTime: "6 min",
            lede: "Pouca evidência não significa pouco risco — significa pouco conhecimento. Este é o balanço objetivo do que foi observado e do que preocupa teoricamente.",
            sections: [
                { h: "O que os estudos relataram", p: ["Nos estudos de fase 1 e 2, os eventos mais frequentes foram leves: rubor (sensação de calor e vermelhidão), dor de cabeça, tontura passageira e reações no local de aplicação, como dor ou irritação.", "A ausência de efeitos graves nesses estudos precisa de contexto: amostras pequenas, duração curta e supervisão médica integral — condições muito diferentes do uso crônico informal."] },
                { h: "Os riscos teóricos do eixo GH/IGF-1", p: ["A elevação crônica e não monitorada de GH/IGF-1 tem uma lista conhecida de preocupações fisiológicas: retenção hídrica, dor articular, resistência à insulina e — a mais séria, ainda que teórica — estímulo ao crescimento de tecidos, motivo pelo qual histórico de neoplasias é uma contraindicação padrão em qualquer terapia que eleve GH.", "Esses riscos são da fisiologia do eixo, não especulados para a molécula: qualquer estimulante de GH carrega o mesmo pano de fundo, e é por isso que terapias legítimas desse eixo exigem exames e acompanhamento endocrinológico."] },
                { h: "O alerta para atletas: WADA", p: ["A ipamorelin integra a Lista de Substâncias Proibidas da Agência Mundial Antidoping (WADA), na classe S2 — hormônios peptídicos, fatores de crescimento e substâncias relacionadas. A proibição vale dentro e fora de competição.", "Atletas de modalidades com controle de doping podem ser sancionados mesmo sem intenção de melhorar performance — e 'produto de pesquisa' não é defesa regulamentar."] },
            ],
            stat: { value: "S2", label: "classe da ipamorelin na Lista de Substâncias Proibidas da WADA — dentro e fora de competição" },
            faqs: [
                { q: "A ipamorelin é segura?", a: "Nos poucos estudos existentes, os eventos foram leves — mas não há dados de longo prazo nem de uso crônico. Os riscos teóricos da elevação de GH/IGF-1 (retenção hídrica, resistência à insulina, crescimento tecidual) tornam o uso sem acompanhamento médico imprudente." },
                { q: "Ipamorelin causa retenção de líquido?", a: "Retenção hídrica é um efeito conhecido da elevação de GH em geral. Relatos desse tipo existem no uso informal, mas não há estudos que quantifiquem esse efeito especificamente para a ipamorelin." },
            ],
            refs: [
                { label: "WADA — Lista de Substâncias Proibidas", url: "https://www.wada-ama.org/en/prohibited-list" },
                { label: "PubMed — ipamorelin safety", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ipamorelin+safety" },
            ],
        },
        {
            slug: "ipamorelin-preco",
            chapter: "06",
            kicker: "Mercado e regulação",
            title: "Preço da Ipamorelin: por que não existe valor oficial",
            description: "Pesquisando o preço da ipamorelin? A resposta honesta: não existe preço oficial, porque a molécula não tem registro em nenhum país. Entenda o mercado informal e seus riscos.",
            keyword: "ipamorelin preço",
            readTime: "5 min",
            warning: true,
            lede: "Se você chegou aqui buscando quanto custa a ipamorelin, a resposta técnica é curta: não existe preço oficial. O que existe — e importa saber — é o porquê.",
            sections: [
                { h: "Sem registro, sem preço", p: ["Preço oficial pressupõe registro sanitário: laboratório detentor, indicação aprovada, cadeia de distribuição certificada. A ipamorelin não tem nada disso — o desenvolvimento farmacêutico foi descontinuado na fase 2 e nenhuma agência do mundo a aprovou.", "Ela também não consta das listas de insumos permitidos para manipulação no Brasil — ou seja, nem a via magistral é um caminho regular."] },
                { h: "E os anúncios 'para pesquisa' que circulam por aí?", p: ["A roupagem comum é a de 'peptídeo para pesquisa' ou 'uso laboratorial'. Na prática, o destino é o consumo humano — e o rótulo de pesquisa é justamente o que exime o vendedor de qualquer padrão farmacêutico: sem garantia de identidade, pureza, concentração ou esterilidade.", "Análises independentes de peptídeos do mercado cinza, publicadas na literatura forense, já encontraram de tudo: subdosagem, contaminação bacteriana e frascos com substância diferente da anunciada."] },
                { h: "O que fazer enquanto isso", p: ["Se a questão é saúde — energia, composição corporal, envelhecimento —, o caminho racional é investigar com um médico as causas e as opções aprovadas. Deficiência real de GH, por exemplo, tem diagnóstico laboratorial e tratamento regulado.", "Nossa consultoria educacional oferece uma avaliação gratuita exatamente para isso: entender seu contexto, explicar o cenário com base na ciência e indicar os próximos passos legítimos — sem venda de peptídeo irregular, jamais."] },
            ],
            stat: { value: "R$ 0", label: "é o preço oficial da ipamorelin — porque nenhum laboratório pode precificar uma molécula sem registro" },
            faqs: [
                { q: "Qual é o preço da ipamorelin?", a: "Não existe preço oficial: a molécula não tem registro em nenhum país. Qualquer valor anunciado refere-se a produtos irregulares do mercado informal, sem garantia de conteúdo." },
                { q: "Ipamorelin manipulada é confiável?", a: "A ipamorelin não consta das listas de insumos permitidos para manipulação magistral no Brasil. Sem insumo de referência e sem fiscalização, não há como garantir identidade, pureza ou dose." },
            ],
            refs: [
                { label: "ANVISA — portal oficial", url: "https://www.gov.br/anvisa" },
                { label: "PubMed — análises de peptídeos do mercado informal", url: "https://pubmed.ncbi.nlm.nih.gov/?term=counterfeit+peptides" },
            ],
        },
        {
            slug: "onde-comprar-ipamorelin",
            chapter: "07",
            kicker: "Disponibilidade",
            title: "Onde comprar Ipamorelin? O status real de disponibilidade",
            description: "Onde comprar ipamorelin com segurança? A resposta direta: não existe canal legal de venda — no Brasil e no mundo. Veja os riscos do mercado informal e os caminhos legítimos.",
            keyword: "ipamorelin onde comprar",
            readTime: "5 min",
            warning: true,
            lede: "Uma das perguntas mais buscadas sobre peptídeos no Brasil. A resposta honesta não é uma lista de fornecedores — é um mapa da realidade regulatória.",
            sections: [
                { h: "A resposta direta", p: ["Não existe onde comprar ipamorelin legalmente. A molécula não foi aprovada por nenhuma agência regulatória do mundo, não tem registro na ANVISA e não está entre os insumos permitidos para manipulação magistral no Brasil.", "Isso vale para qualquer formato: frascos injetáveis, 'kits de pesquisa', blends com outros peptídeos ou produtos importados anunciados em redes sociais e marketplaces."] },
                { h: "O risco por trás do mercado informal", p: ["A venda de peptídeos sem registro virou alvo recorrente de alertas e ações da ANVISA e das vigilâncias sanitárias estaduais. Para o comprador, o problema não é só legal: um produto injetável sem cadeia certificada carrega risco de contaminação, erro de concentração e falsificação.", "E há um agravante para atletas: a ipamorelin é proibida pela WADA, e a contaminação cruzada em produtos do mercado cinza é uma causa documentada de doping não intencional."] },
                { h: "Os caminhos legítimos que existem hoje", p: ["Se a sua questão envolve o eixo GH — fadiga, composição corporal, recuperação, envelhecimento —, a rota legítima é a avaliação médica: um endocrinologista pode investigar deficiências reais com exames e, se houver indicação, prescrever terapias aprovadas e monitoradas.", "Nossa consultoria educacional em peptídeos ajuda nesse primeiro passo: uma avaliação gratuita para alinhar expectativas, explicar o cenário e mapear os próximos passos legítimos para o seu caso."] },
            ],
            stat: { value: "0", label: "canais legais de venda de ipamorelin no Brasil e no mundo — qualquer oferta atual é irregular" },
            faqs: [
                { q: "Onde comprar ipamorelin online?", a: "Não existe canal legal online ou físico. Sites e perfis que vendem 'ipamorelin' operam no mercado informal, sem garantia de conteúdo, e esse comércio já foi alvo de ações da ANVISA." },
                { q: "Posso importar ipamorelin para uso pessoal?", a: "A importação de substância sem registro não garante legalidade nem segurança, e produtos injetáveis sem cadeia certificada carregam risco sanitário grave. Converse com um médico sobre alternativas aprovadas." },
            ],
            refs: [
                { label: "ANVISA — portal oficial", url: "https://www.gov.br/anvisa" },
                { label: "WADA — Lista de Substâncias Proibidas", url: "https://www.wada-ama.org/en/prohibited-list" },
            ],
        },
    ],
};
